### ISSUE TITLE
unable to configure ssl for independent setup

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud#104]
there is no sample localhost ssl certificate, nginx.conf.original file and update in `listen 80` if we setup MCloud independently.
let's investigate possibility to make it happen

**Comment by vdelendik** [comment]
fixed. setup MCloud from this repo independently using https and port 443
-> everything should start automatically, localhost self-signed certificates used by default, i.e. browsers will complain about it but it is expected. On chrome you should be able to press advanced and continue

**Comment by dhreben** [comment]
Fixed.
