### ISSUE TITLE
Failed to launch STF

### ISSUE THREAD

**Issue by coolalexhuang** [zebrunner/mcloud#105]
I have followed the user guide to install mcloud, but fails to open SFT website, could you please help?

Log:
Status: Downloaded newer image for nginx:1.17
Creating mcloud-grid      ... done
Creating rethinkdb   ... done
Creating stf-triproxy-app         ... done
Creating stf-triproxy-dev         ... done
Creating stf-processor001         ... done
Creating stf-websocket            ... done
Creating stf-reaper               ... done
Creating stf-migrate              ... done
Creating stf-auth                 ... done
Creating stf-api-groups-engine    ... done
Creating stf-storage-temp         ... done
Creating stf-api                  ... done
Creating stf-app                  ... done
Creating stf-storage-plugin-image ... done
Creating stf-storage-plugin-apk   ... done
Creating stf-proxy                ... done
![image](https://user-images.githubusercontent.com/2528449/139071436-3a04218a-c154-462c-a84f-55b1d5a6e8c0.png)

Open URL: http://localhost:8888/stf , the page keeps loading and fails eventually.

**Comment by vdelendik** [comment]
@coolalexhuang, please specify version you use, is it latest 1.7?
And 2nd, share please logs of the stf-proxy and stf-app containers

**Comment by vdelendik** [comment]
closing as no information provided
