### ISSUE TITLE
Implement independent service for uploading of tested builds on mcloud machine

### ISSUE THREAD

**Issue by SergeiZagriychuk** [zebrunner/mcloud#112]
Right now we produce tmp link to the tested app located in S3 and further use it for uploading to device via Appium.
Because of network or Amazon issues uploading to device from s3 might take a lot of time and affect general tests execution performance.

The idea is to implement independent service which will be installed to machine with mcloud-ios and mcloud-android and which will download and store artefacts to the same machine per request. It will store apps by predefined path on the machine.
Later that path will be sent to Appium during the test so each time application will be downloaded from the same machine where device is connected but not from remote s3 bucket.
So that app downloading from s3 will happen only once per entire suite run.
It should increase app uploading operation and positively affect entire test suite performance.

**Comment by vdelendik** [comment]
done and tested on my own. in additions ansible script updated to use independent docker volume for appium local storage...

**Comment by vdelendik** [comment]
testing confirmed that multithreading execution is fine. 1st thread lock filesystem by key and only after finishing download other threads start using new component. Also tested use-case when file size is different and it works as expected. In case of any re-upload new artifact will be re-downloaded as well
