### ISSUE TITLE
register admin@zebrunner.com as default stf admin

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud#114]
we have to provide example howto add stf admin person making admin/admin@zebrunner.com as default one

**Comment by vdelendik** [comment]
done, setup community-edition from branch develop and setup enabling mcloud.
login as user: admin; email: admin@zebrunner.com
-> verify that you have permissions to manage `Groups`. Default group should be named `MCloud`

**Comment by okamara** [comment]
<img width="1349" alt="Снимок экрана 2021-12-29 в 18 55 40" src="https://user-images.githubusercontent.com/32964663/147680481-c2f7c24b-7fc1-467d-b881-eae3a86b807f.png">

**Comment by okamara** [comment]
verified -> login as user: admin; email: admin@zebrunner.com
-> verify that you have permissions to manage Groups. Default group should be named MCloud
