### ISSUE TITLE
2.0: renaming sub-components

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud#116]
due to the upcoming 2.0 release we have to do global renaming:
1. [DONE] mcloud-android -> mcloud-agent
2. [DONE] android-device-> mcloud-device
3. [DONE] mcloud-appium is decommissioned and new appium should be used
4. mcloud-ios -> seems to be simulators only

**Comment by vdelendik** [comment]
done. appium repo made public as well: https://github.com/zebrunner/appium

**Comment by dhreben** [comment]
Verified
