### ISSUE TITLE
investigate an option to move mcloud-grid to agent instance with devices or to independent repo

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud#118]
current repository handle all aspects of mCloud with STF, i.e. services and ui for manual devices usage via STF.
mcloud-grid is enhanced selenium hub and is part of the automation. 
So far idea was to move it into the mcloud-agent (former mcloud-android) to be as close as possible to the devices.
At the same time starting from 2.0 the most serious video upload operation going to be moved onto the appium itself, i.e. grid again is light-wieght...
So let's investigate the possibility to make mcloud-grid fully independent solution which might be a part of the community-edition as mcloud itself.

**Comment by vdelendik** [comment]
final decision was to keep it as part of mcloud repo as is. closing as won't fix

**Comment by dhreben** [comment]
won't fix.Closed
