### ISSUE TITLE
bump up to 2.0 mcloud-grid

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud#119]
Use latest 2.0 mcloud-grid where we removed completely video uploader.
Make sure to adjust setup process and default variables.env accordingly

**Comment by vdelendik** [comment]
done. testing might be done on personal aws instances using community-edition from develop branch.
Verify that setup/strat/stop/backup/restore and shutdown works as expected without any errors in console

**Comment by dhreben** [comment]
Verified.
