### ISSUE TITLE
improve setup to be able to customize default admin name and email

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud#120]
we already register default one: https://github.com/zebrunner/mcloud/issues/114
but it would be great to ask during setup actual values from cli

**Comment by vdelendik** [comment]
done. to test we have to cover 2 scenarios having community-edition and mcloud setup independently.
scenario #1:
1. clone this mcloud repo 
2. execute `./zebrunner.sh setup` providing custom admin username and email
3. start services
4. login based on mock auth using provided admin username and email
-> verify that you have access to groups (admin privileges)
5. logout and login again using another name/email
-> access to groups not exists

**Comment by dhreben** [comment]
Verified.
