### ISSUE TITLE
provide skeleton for the basic auth for selenium hub

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud#122]
need easy way to setup basic auth for the mcloud selenium hub.

**Comment by vdelendik** [comment]
done. during the testing please
1. generate creds and enable them based on steps in https://github.com/zebrunner/mcloud/blob/develop/configuration/stf-proxy/htpasswd/README.md
2. run demo iOS/Android jobs
-> they should fail due to the access issue
3. register authenticated mcloud grid url in CE and run iOS/Android demo jobs
-> jobs should be executed successfully
4. test backup/restore - generated mcloud.htpasswd should be backuped and restored accordingly
5. and finally make sure that shutdown remove `configuration/stf-proxy/htpasswd/mcloud.htpasswd` file

**Comment by dhreben** [comment]
Verified
