### ISSUE TITLE
made ssl.crt and ssl.key not under source control

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud#136]
let's keep default self-signed under ssl.crt.original and ssl.key.original.
only during setup we should copy them into the ssl.crt and ssl.key.
also ssl.crt and ssl.key should be added into the .gitignore

**Comment by vdelendik** [comment]
done. to test please 
1. setup https setup from scratch using branch develop.
-> self-signed certificate and key are used
2. shutdown, put valid crt and key into the `configuration/stf-proxy/ssl/ssl.crt` and `configuration/stf-proxy/ssl/ssl.key` in advance
3. execute `./zebrunner.sh setup`
-> custom ssl files should be used (non self-signed)
-> `git status` command shouldn't show modified key and crt
4. execute `./zebrunner.sh backup`
-> `configuration/stf-proxy/ssl/ssl.crt.bak` and `configuration/stf-proxy/ssl/ssl.key.bak` should be generated
5. update key and crt and execute `./zebrunner.sh restore`
-> original crt and key are restored
6. execute `./zebrunner.sh shutdown`
-> `configuration/stf-proxy/ssl/ssl.crt` and `configuration/stf-proxy/ssl/ssl.key` removed

**Comment by vdelendik** [comment]
@dhreben, please verify items: 1, 4 and 5
for number 1 - you should see 2 extra echo messages about using self-sign certificate and key

**Comment by dhreben** [comment]
Verified:
1.
```
using self-signed certificate...
using self-signed key...
```
4. ssl.crt.bak and ssl.key.bak are generated after ./zebrunner.sh backup
5. ssl.crt and ssl.key are restored after ./zebrunner.sh restored
