### ISSUE TITLE
Screenshots not visible (Android)

### ISSUE THREAD

**Issue by vaclcer** [zebrunner/mcloud#139]
When creating a screenshot from STF GUI, the picture is created and saved into "mcloud-21_stf-temp-volume" docker volume. I can confirm the picture itself exists in "/var/lib/docker/volumes/mcloud-21_stf-temp-volume/_data" path at host. But it cannot be seen, nor opened,  in STF GUI. Permissions inside "stf-temp-volume" container look good. Is this a bug?

Using mCloud 2.1. Thanks!

![image](https://user-images.githubusercontent.com/39984150/167094736-4ca9a2d1-6e31-4e8a-8c43-271086465697.png)
![image](https://user-images.githubusercontent.com/39984150/167094855-bf41af55-81b9-45cc-b988-922a1421ea48.png)
![image](https://user-images.githubusercontent.com/39984150/167095673-bc75f20b-22c5-4677-9142-ebdc6d436cbd.png)

**Comment by vdelendik** [comment]
@vaclcer, it is prohibited to run everything under the root when you play with docker. it corrupts shared permissions.
