### ISSUE TITLE
Error: No such file or directory mcloud.htpasswd.bak after ./zebrunner.sh restore and backup

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud#147]
**Steps:**

Case 1:

1./zebrunner.sh restore
 
**Actual result:** cp: cannot stat 'configuration/stf-proxy/htpasswd/mcloud.htpasswd.bak': No such file or directory

Case 2:

1./zebrunner.sh backup

**Actual result:** cp: cannot stat 'configuration/stf-proxy/htpasswd/mcloud.htpasswd.bak': No such file or directory

**Comment by vdelendik** [comment]
fixed.

**Comment by dhreben** [comment]
Fixed
