### ISSUE TITLE
incorporate upgrade steps into the setup

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud#149]
to move CE upgrade steps (https://github.com/zebrunner/community-edition/issues/491) into the sub-modules we have to support automatic detection of manual intervention inside variables.env for any value aka STF_TOKEN, SECRET, AUTHKEY, STF_ADMIN_NAME, STF_ADMIN_EMAIL and STF_ROOT_GROUP_NAME

**Comment by vdelendik** [comment]
done. it might be tested during upgrade and using syntenic steps below:
1. setup mcloud independently using branch develop (don't start services)
2. update variables.env putting non-default values for below vars, for example:
```
AUTHKEY=mykey2
SECRET=password2
STF_TOKEN=264221c783ab41cc8e175b2227e50178a3505ec056514b4a88c9ada92bdaf623
STF_ROOT_GROUP_NAME=MCloud2
STF_ADMIN_NAME=admin2
STF_ADMIN_EMAIL=admin2@zebrunner.com
```
3. start and do basic testing of availability of STF/MCloud grid etc
4. run `./zebrunner.sh setup` again
-> all custom settings should be saved in variables.env!

**Comment by okamara** [comment]
Verified on develop branch, fixed.
