### ISSUE TITLE
register backup variables files generated during upgrade

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud#150]
from time to time we have to regenerate .env and variables.env during upgrade. in this case we always do a backups:
.env -> .env_2.0
variables.env -> variables.env_2.0

all these temp files should be ignored by git

**Comment by vdelendik** [comment]
done. to test do an upgrade testing from CE 2.0->2.1 and execute after upgrading this command: `git status`
-> no modified/untracked files should be detected

**Comment by okamara** [comment]
Verified, fixed.
