### ISSUE TITLE
investigate dashes removal from iOD devices udid during registration

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud#155]
As we use go ios utility now for linux and mac agents we can test an option to remove all dashes from iOD device udids.
Go ios identify such devices without dashes in udid. native iOS we don't use anymore.
So the only question is appium automation code. if it can handle without dashes as well then we can review all kind of workarounds and remove them but add into the readme that iOS device udid should be declared as it is detected by go ios, i.e. without dashes!

related tickets: 
https://github.com/zebrunner/stf/issues/565
https://github.com/zebrunner/mcloud-device/issues/110
https://github.com/zebrunner/appium/issues/219
and some places exists in bash startup scripts for appium and stf as well.

**Comment by vdelendik** [comment]
all sub components updated in 2.5.2 milestone

**Comment by dhreben** [comment]
Verified on prod
