### ISSUE TITLE
bump up to rethinkdb 2.4.2

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud#175]
2.4.2 rethinkdb is amd64 compatible and might be used for Mac M1

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/mcloud/pull/174.
testing should include setup of this repo or CE from develop branch and registering devices... 
basic acceptance after deployment should be enough. Already tested on M1

**Comment by dhreben** [comment]
Verified. Did basic acceptance including manual usage inside STF
