### ISSUE TITLE
investigate an option to use direct stf-api for internal communication

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud#177]
as of now we use STF_URL and token from [variables.env](https://github.com/zebrunner/mcloud/blob/da3547711eea5972f1b477c1c402eb7c0793ce75/docker-compose.yml#L24).
It uses external ip address and might route externally.

we can keep STF_URL as is but override among other envitonment variable for mcloud-grid only using:
```
     - STF_URL=http://stf-api:3000/
```

above update will guarantee routing internally inside the same docker network.

**Comment by vdelendik** [comment]
done. for testing it should be enough to do setup, generate and reuse STF_TOKEN.
During mobile testing double check that devices are occupied by user in STF.

**Comment by dhreben** [comment]
Verified
