### ISSUE TITLE
handle secondary shutdown

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud#180]
similar ticket: https://github.com/zebrunner/reporting/issues/2344

**Comment by vdelendik** [comment]
fixed. we should see `Unable to erase as nothing is configured!` warning in case of executing shutdown without setup or during secondary shutdown

**Comment by dhreben** [comment]
Verified.

**Case 1:**
1. Git clone mcloud repo
2. cd mcloud
3. ./zebrunner.sh shutdown  -> without setup -> 
```
(base) build@mcloud:~/tools/1/mcloud$ ./zebrunner.sh shutdown

      WARNING! Unable to erase as nothing is configured!
```

**Case 2:**
1. cd mcloud on working repo
2. ./zebrunner.sh shutdown - Select yes -> 
```
(base) build@mcloud:~/tools/community-edition/mcloud$ ./zebrunner.sh shutdown

      WARNING! Shutdown will erase all settings and data for "/home/build/tools/community-edition/mcloud"!
      Do you want to continue? y/n [n]:y
Network infra is external, skipping
Removing volume mcloud_stf-temp-volume
Removing volume mcloud_stf-db-volume
```
3. ./zebrunner.sh shutdown -> again ->
```
(base) build@mcloud:~/tools/community-edition/mcloud$ ./zebrunner.sh shutdown

      WARNING! Unable to erase as nothing is configured!
```
