### ISSUE TITLE
integrate auth-zebrunner for CE setup in mcloud

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud#181]
when all bundle is configured let's automatically setup auth-zebrunner-ce instead of auth-mock.
that's allow to unify authentication in reporting and mcloud using the same auth system.

also make sure that independent mcloud setup continue to use mock or might configure ldpa/oauth automatically via setup? 

related ticket is https://github.com/zebrunner/stf/issues/524

**Comment by vdelendik** [comment]
done. if we configure CE globally we should setup `auth-zebrunner` by default, i.e. credentials from reporting users might be logged to stf. if we setup mcloud independently them we continue to setup auth-mock, i.e. any user/email might log into the stf

**Comment by dhreben** [comment]
**Steps:**

1.  git clone --recurse-submodule --branch develop https://github.com/zebrunner/mcloud.git
2. cd mcloud
3. add ssl
4. ./zebrunner.sh setup
5. Open STF

**Actual result:**` auth-zebrunner` is absent after mcloud setup

<img width="398" alt="Screenshot 2023-04-27 at 19 23 57" src="https://user-images.githubusercontent.com/50950954/234927685-599ae6af-9e3c-4a90-97ef-7e1210e2b0e1.png">
