### ISSUE TITLE
Add support for for ReDroid

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [zebrunner/mcloud#191]
It might be worth adding support for ReDroid in order to create fast android emulators 

https://github.com/remote-android/redroid-doc

**Comment by vdelendik** [comment]
redroid 8.1.0-13.0.0 already supported as part of zebruner selenium grid: https://zebrunner.com/selenium-grid

**Comment by vdelendik** [comment]
that's tuned repository for redroid emulator usage:
https://github.com/zebrunner/mcloud-redroid/releases/tag/1.0
