### ISSUE TITLE
certify wda 5.13.0 

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud#208]
I synced and merged 5.13.0 changes into the master branch of our forked repo: https://github.com/zebrunner/WebDriverAgent
@dhreben, please reuse this code sources to test and certify webdriveragent.ipa and via macOS (for ios17+)

**Comment by dhreben** [comment]
Tested on Mac with 17+ iOS version.

**Comment by dhreben** [comment]
Verified.
