### ISSUE TITLE
Docker compose plugin compatibility

### ISSUE THREAD

**Issue by azarouski** [zebrunner/mcloud#214]
Let's modify `zebrunner.sh` file to correspond docker compose plugin.
We need to replace `docker-compose` with `docker compose` command and additionally check compatibility and possible weak points.

**Comment by vdelendik** [comment]
related ticket is https://github.com/zebrunner/community-edition/issues/587

**Comment by vdelendik** [comment]
done. to test - seup CE from scratch and test strat/stop/down

**Comment by dhreben** [comment]
Verified.
