### ISSUE TITLE
Unable to access hostname / stf page. 

### ISSUE THREAD

**Issue by MHabiib** [zebrunner/mcloud#220]
After executing the './zebrunner.sh start' command, the container appears to be running properly. However, I have encountered difficulties accessing the host, and it takes an extended period to respond, ultimately leading to a timeout. I kindly request your assistance in resolving this matter. Thank you for your attention to this issue
<img width="996" alt="image" src="https://github.com/zebrunner/mcloud/assets/42311916/86665514-62fd-47a7-b861-8c36c54b6303">

**Comment by vdelendik** [comment]
@MHabiib, need more details. It seems configuration issue on your side

**Comment by vdelendik** [comment]
closing due to the inactivity. @MHabiib, feel free to ask about help in https://t.me/zebrunner
