### ISSUE TITLE
update grid timeouts to use SECONDS!

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud#223]
we have values in ms but in reality it is seconds!
```
     - GRID_TIMEOUT=60000
     - GRID_BROWSER_TIMEOUT=60000
```

let's use 60 as it is default value

**Comment by akamarouski** [comment]
According to the https://github.com/zebrunner/mcloud-grid/issues/145 by default we will use:
 GRID_NEW_SESSION_WAIT_TIMEOUT 600000 milliseconds (10 min)
 GRID_BROWSER_TIMEOUT 0
 GRID_TIMEOUT 150 (seconds)

**Comment by vdelendik** [comment]
done. setup CE from scratch using branch develop and execute basic automation mobile tests is enouh

**Comment by dhreben** [comment]
Verified.
CE+mcloud-agent installed from scratch
Basic acceptance with iOS-Preferences-Test ,Mobile-iOS-Safari-Test , Android-Demo-Test successfully completed. Video, screenshots and logs are available
