### ISSUE TITLE
Connection is lost too often and user Need to retry connection

### ISSUE THREAD

**Issue by okamara** [zebrunner/mcloud#38]
Steps:
1. Open and sign in http://stage.solvd.com/#!/devices
2. Go somewhere and come back In 2 mins
Actual result: Need to retry connection

<img width="688" alt="Screen Shot 2020-03-11 at 2 33 37 PM" src="https://user-images.githubusercontent.com/32964663/76412921-904de880-63a5-11ea-86b1-c98af9569806.png">

**Comment by vdelendik** [comment]
Fixed. It should be verified using zebrunner/zebrunner (branch: develop) and your own env.
stage.solvd.com is not a good variant for that anymore

**Comment by dhreben** [comment]
Tested on my env.
Issue not reproduced.
