### ISSUE TITLE
Rename mock/ldap/oauth stf container 

### ISSUE THREAD

**Issue by okamara** [zebrunner/mcloud#43]
Need single name stf-auth

**Comment by ilya-varchenya** [comment]
https://github.com/zebrunner/mcloud/pull/44

**Comment by vdelendik** [comment]
merged. acceptance criteria - user should be able to login into the stf afetr installing infra from zebrunner/zebrunner (branch: develop)

**Comment by okamara** [comment]
Verified. Fixed.
