### ISSUE TITLE
selenium-hub should depends on stf-app container 

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud#46]
add this conditio to selenium-hub docker container
    depends_on:
      - stf-app

in case hub started first it can't establish STF connection and all tests failed as no access to adb connect host:port

**Comment by ilya-varchenya** [comment]
https://github.com/zebrunner/mcloud/pull/47

**Comment by ilya-varchenya** [comment]
Test scenario:
1. clone repo
2. ./zebrunner.sh start
3. docker ps -a
4. container's statuses should look like that:
![image](https://user-images.githubusercontent.com/44428408/94019368-5d57c900-fdba-11ea-9d5a-0cd0859ac7b6.png)

**Comment by dhreben** [comment]
Fixed
