### ISSUE TITLE
At startup mcloud redirects to localhost

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud#53]
Test scenario:

1.Clone mcloud
2.Nano mcloud/docker-compose.yml
3.Change port to "80:80"
4.Open browser and enter ip instance:80/stf

**Actual result:** At startup mcloud redirects to localhost
Please see screenshot:

<img width="921" alt="Screen Shot 2020-10-07 at 17 52 19" src="https://user-images.githubusercontent.com/50950954/95347698-db8d9280-08c5-11eb-9737-f2081d600344.png">

**Comment by vdelendik** [comment]
closed ticket as dupe of #53. no need to test this one
