### ISSUE TITLE
'CocoaAsyncSocket/GCDAsyncSocket.h' file not found

### ISSUE THREAD

**Issue by tepmehatop** [zebrunner/mcloud#54]
Hello dear friends,

trying to setup IOS farm, but stack on step 
### Sign WebDriverAgent using your Dev Apple certificate and install WDA on each device manually

- Install Appium 1.18.3 - done
- Install node v13.14.0 (npm v6.14.4)   - done
- Choose WebDriverAgentRunner and your device( iphone 7)  - done
- Choose your dev certificate - done

When i try to run test i get error
`'CocoaAsyncSocket/GCDAsyncSocket.h' file not found`

`
/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgentLib/Vendor/RoutingHTTPServer/RoutingHTTPServer.m:1:9: In file included from /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgentLib/Vendor/RoutingHTTPServer/RoutingHTTPServer.m:1:
`

![image](https://user-images.githubusercontent.com/12258635/95795921-4559d200-0cf4-11eb-9d78-4453060dc589.png)

Hope for any help,
Thank's 
Mark.

**Comment by emirhansarac29** [comment]
Hey Mark,

you should run "./Scripts/bootstrap.sh" this command in where WebDriverAgent located. That will install dependencies.
