### ISSUE TITLE
ios-slave set_selenium_properties values

### ISSUE THREAD

**Issue by emirhansarac29** [zebrunner/mcloud#55]
I'm trying to run stf in iOS but I did not get the real values in the set_selenium_properties.sh file. Can someone explain me what should I set those variables?
-STF_PUBLIC_HOST
-STF_PRIVATE_HOST
-WEBSOCKET_PROTOCOL
-WEB_PROTOCOL
-hubHost
-hubPort
-STF_PUBLIC_NODE_HOST
-STF_PRIVATE_NODE_HOST

**Comment by vdelendik** [comment]
SmartTestFarm recommend to use public and private ip addresses for the same service to organize valid traffic between service using private ip address and internal routing. Public ip address is used for clients(browser) to be able to reuse private resources...
So to make story short:
1) These two ip addresses should refer to the central Linux server where main STF service are running
-STF_PUBLIC_HOST
-STF_PRIVATE_HOST
Note: if you don't have public/private addresses and deploy everything inside private network - feel free to sue the same address.

2) Below arguments by default use http and ws unsecured protocols and must be updated to https and wss if SSL is configured.
-WEBSOCKET_PROTOCOL
-WEB_PROTOCOL

3) These ones describe your mac slave with devices. 
-STF_PUBLIC_NODE_HOST
-STF_PRIVATE_NODE_HOST
Note: use the same internal ip address value if no public access expected

4) And finally selenium hub host and port variables so local appium on mac slave could connect and register devices.
-hubHost
-hubPort
by default we have enhanced selenium hub on central Linux machine on port 4446:
https://github.com/zebrunner/mcloud/blob/948524ae8fbe2bea4cf5e2f32d9a4e04cc81d955/docker-compose.yml#L40


@emirhansarac29, let me know if you still have any questions or problems
