### ISSUE TITLE
Mcloud selenium hub does not return device after timeout on nginx

### ISSUE THREAD

**Issue by okamara** [zebrunner/mcloud#58]
Steps:
1. Request driver session on mcloud from external network
2. If driver not started during timeout - we got exception [#285]
3. Carina tries to occupy the same device
-> Selenium hub doesn't return device on stf 
->  Huge queue is created in the result

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/mcloud/commit/948524ae8fbe2bea4cf5e2f32d9a4e04cc81d955

to test just to clone recursively zebrunner using develop branch and verify that such variables added into the mcloud/docker-compose.yml (selenium-hub container)
`     - GRID_NEW_SESSION_WAIT_TIMEOUT=240000
     - GRID_TIMEOUT=60000
     - GRID_BROWSER_TIMEOUT=60000`

**Comment by okamara** [comment]
Verified. Fixed.
