### ISSUE TITLE
move ios-slave into independent repository

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud#65]
the is no sense to keep it anymore as branch.
this code should be placed into the independent repo with valid readme just for iOS mobile device farm

**Comment by vdelendik** [comment]
done fir iOS and Android: 
https://github.com/zebrunner/mcloud-ios
https://github.com/zebrunner/mcloud-android

during the testing please verify all links in reamde for all 3 repositories including this one

**Comment by okamara** [comment]
Will be tested after 1.3 release.

**Comment by dhreben** [comment]
Verified.
