### ISSUE TITLE
sync with latest 3.5.0 version from deviceFarmer

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud#70]
review the changes andmerge if possible into our stf related part

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/mcloud/commit/41847f46882ffcce548220799dd2ca9012997e6b
merge happened in zebrunner/stf:1.0-beta1 docker image.


actual merge commit in stf project: https://github.com/zebrunner/stf/commit/a807a8048f281a391f9fdd08ea37d4e5d416c853

**Comment by dhreben** [comment]
Verified.
