### ISSUE TITLE
remove ftp container and all references inside mcloud

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud#71]
mcloud still uses their own ftp server to store video recording. need investigate if we can consolidate s3 compatible storage and ftp using below container or similar:
https://github.com/Factual/open-dockerfiles/tree/master/s3-backed-ftp

**Comment by vdelendik** [comment]
new Zebrunner selenium-hub will have their own direct s3 integration. So ftp should be removed completely from the mcloud

**Comment by vdelendik** [comment]
done

**Comment by dhreben** [comment]
Verified.
