### ISSUE TITLE
remove STF_HOST_PROVIDER_PUBLIC for iOS and Android

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud#76]
https://github.com/zebrunner/stf/issues/171

no need to provide public access to stf node (android and ios) anymore if above ticket is solved^^^

**Comment by vdelendik** [comment]
done for all repositories.
as a test scenario 
1. Configure android and ios slave using updated manual
-> devices should be registered in STF
2. Occupy device and open "Automation" tab
-> Appium url should be somethig like `http://public-ip:7403/wd/hub`
3. Try to do any call to this shared appium url, for example /status
```
curl http://myhost:7403/wd/hub/status
```
-> appium should return it's status and version in output
4. Stop usage for device
5. again execute status call `curl http://myhost:7403/wd/hub/status`
-> this time error message should appear
```
curl: (7) Failed to connect to myhost port 7403: Connection refused
```

**Comment by dhreben** [comment]
Closed.
Opened new ticket https://github.com/zebrunner/mcloud-ios/issues/16
