### ISSUE TITLE
reuse bash replace instead of sed call

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud#78]
`sed -i` is not supported on mac platforms. we have to reuse `replace` bash functiona instead. Later it should allow to support Mac platforms for MCloud master host (for now only Linux)

**Comment by vdelendik** [comment]
done. during testing it is recommended to setup zebrunner with MCloud using AWS S3 storage.
Mobile android demo job should be able to run and produce screenshot/video artifacts

**Comment by dhreben** [comment]
Verified.
