### ISSUE TITLE
handle appium urls location via general nginx

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud#80]
Each device service register as appium url:
http://${publicIp}/stf/appium/${host}/${port}/wd/hub

So using `/stf` general NGiNX will redirect to stf-proxy service.
stf-proxy service should parse host and port and proxy pass to appium using private network connection

**Comment by vdelendik** [comment]
Fixed. Such location match was added onto the stf-proxy nginx:
```
    # Handle appium-providers
    location ~ "^/appium/(?<appiumprovider>([^/]+))/(?<port>[0-9]+)/$" {
      proxy_pass http://$appiumprovider:$port/;
    }
```

To test setup zebrunner from develop branch, open any device (Both Android and iOS!!!).
Copy from Automation tab link to appium: http://${publicIp}/stf/appium/${host}/${port}/wd/hub

Open http://${publicIp}/stf/appium/${host}/${port}/wd/hub/status in browser 
-> you should see status response from Appium with appium version

**Comment by dhreben** [comment]
Verified.
