### ISSUE TITLE
Error at startup device

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud#84]
**Test scenario:**

1.Open ec2 instance link/stf
2.Tap to any device

**Actual result:** Error: Service is currently unavailable.Try to attempt later after open device

<img width="809" alt="Screenshot 2021-02-24 at 17 10 20" src="https://user-images.githubusercontent.com/50950954/109012550-2f591680-76c3-11eb-8e32-27e50c8b49a8.png">

**Comment by vdelendik** [comment]
fixed: https://github.com/zebrunner/mcloud/commit/2d7a24c37a9596128e00945a3e3bce4ffd0e4084

**Comment by dhreben** [comment]
Fixed:

<img width="612" alt="Screenshot 2021-02-24 at 20 15 49" src="https://user-images.githubusercontent.com/50950954/109038733-19584f80-76dd-11eb-9fbb-264dc534fc30.png">
