### ISSUE TITLE
Master can't get the Android Slave var HOST

### ISSUE THREAD

**Issue by shiron-truong** [zebrunner/mcloud#89]
Hi,
I submit this ticket after get support from Vad Del:

In Android slave, I updated in /usr/local/bin/device2docker file
replace
        -e PROXY_PORT=$proxy_port \
->
        -e PORT=$proxy_port \
and add new var
        -e HOST=<value of STF_PRIVATE_HOST>

But in Mcloud  Master get the container host instead of configuration from slave (STF_PRIVATE_HOST).

Could you please help to check it?

Many thanks and best regards,
Binh

**Comment by vdelendik** [comment]
fixed by adding extra appium_port variable.
changes might be tested using zebrunner branch: develop

**Comment by dhreben** [comment]
Verified.
