### ISSUE TITLE
stf-proxy component is too sensitive for services restart 

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud#92]
stf-proxy uses upstream declaration and in case of any service restart for example stf-websocket it potentially couldn't route to new docher host.
We have to review all upstreams and use dynamic bindings via
```
      set $upstream_websocket http://stf-websocket:3000;
      proxy_set_header Host stf-proxy;
      proxy_pass $upstream_websocket;
```

**Comment by vdelendik** [comment]
fixed. during the testing regular setup from zebrunner/zebrunner branch: develop needed including basic acceptance.
Also ni addition we have to test that killing stf-websocket container not corrupt everything, i.e.:
```
./zebrunner.sh start
#do quick testing of STF UI (no need to run jobs etc)
docker rm -f stf-websocket
#while websocket is down you should see disconnected error message
./zebrunner.sh start
#as only stf-websocket is up you could retry and use STF UI again
```
So there is no requirement to restart stf-proxy anymore when any child service was restarted and got new ip address

**Comment by dhreben** [comment]
Fixed.
