### ISSUE TITLE
Location name shown the same name as serial

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud#94]
**Test scenario:**

1.Open demo.zebrunner.farm/stf
2.Click details

 **Actual result**: Location name shown the same name of serial
 **Expected result** :Location must be differ from serial number and include the name of location

<img width="1435" alt="Screenshot 2021-04-28 at 18 51 39" src="https://user-images.githubusercontent.com/50950954/116434252-ef451a00-a852-11eb-8781-8df6344160db.png">

**Comment by vdelendik** [comment]
Default naming will be declared as:
mcloud-android
mcloud-ios

Also they should be be overriden in android using STF_PROVIDER_NAME env var and inside ios via new property

**Comment by vdelendik** [comment]
android-device change: https://github.com/zebrunner/android-device/commit/3e224f09e3332bd027d22ddbc38021064a2573ca

**Comment by vdelendik** [comment]
fixed. after setup from zebrunner develop branch locationby default should bemcloud-android and mcloud-ios instead of device udid.
Also make sense to update it manually to something like NYC-Linux, NYC-Mac

**Comment by dhreben** [comment]
Verified.
